### ISSUE TITLE
Can't load

### ISSUE THREAD

**Issue by vikraman** [ssomayyajula/HoTT#2]
I couldn't load many files because the module name doesn't match the file or it requires something in basic-hott which I don't have.

**Comment by ssomayyajula** [comment]
Forgot to mention--only files under `Pi/` should be loadable. Anything in `scratch` won't load. Which file is giving you issues? I'm looking at the changes I've made to `basic-hott` but nothing is major.

**Comment by vikraman** [comment]
I see, Robert deleted the EmbeddingsInUniverse module which was the problem, going back two commits in basic-hott works. Also, the Pi/Topology/* files don't load but that is ok.

**Comment by ssomayyajula** [comment]
Ah, any reason why he deleted it?

**Comment by vikraman** [comment]
I think he's trying to organize the code by removing the scratch modules.

**Comment by ssomayyajula** [comment]
Alright, I'll close this issue then.
